name: Scheduled Update

on:
  schedule:
    # Runs at 00:00 UTC every Sunday
    - cron: '0 0 * * 0' 
  workflow_dispatch: # Always keep this so you can run it manually anytime

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update_list.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit and Push changes
        run: |
          git config --global user.name "Awesome-Bot"
          git config --global user.email "actions@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Weekly Automated Update: $(date)" && git push)
